import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.bridgeuni.com/api";

// Create the API slice using RTK Query
export const aboutApi = createApi({
  reducerPath: "aboutApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");
      // If a token exists, add it to the headers
      if (token) {
        headers.set("authorization", `${token}`);
      }
      return headers;
    },
  }),

  endpoints: (builder) => ({
    getAllAbout: builder.query({
      query: () => '/aboutUs',
    }),
    getAbout: builder.query({
      query: (id) => '/aboutUs/' + id,
    }),
    addAbout: builder.mutation({
      query: (data) => ({
        url: "/aboutUs",
        method: "POST",
        body: data,
      }),
    }),
    updateAbout: builder.mutation({
      query: ({ id, data }) => ({
        url: `/aboutUs/${id}`,
        method: "PUT",
        body: data,
      }),
    }),
    deleteAbout: builder.mutation({
      query: (id) => ({
        url: `/aboutUs/${id}`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetAllAboutQuery,
  useGetAboutQuery,
  useAddAboutMutation,
  useUpdateAboutMutation,
  useDeleteAboutMutation
} = aboutApi;
