import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.bridgeuni.com/api";

// Create the API slice using RTK Query
export const blogApi = createApi({
  reducerPath: "blogApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      const token = localStorage.getItem("token");
      if (token) {
        headers.set("authorization", `${token}`);
      }
      return headers;
    },
  }),

  endpoints: (builder) => ({
    getBlogs: builder.query({
      query: () => ({
        url: "/blog",
      }),
    }),
    getBlogById: builder.query({
      query: (id) => ({
        url: `/blog/${id}`,
      }),
    }),
    addBlog: builder.mutation({
      query: (blog) => ({
        url: "/blog",
        method: "POST",
        body: blog,
      }),
    }),
    updateBlog: builder.mutation({
      query: ({ id, blog }) => ({
        url: `/blog/${id}`,
        method: "PUT",
        body: blog,
      }),
    }),
    deleteBlog: builder.mutation({
      query: (id) => ({
        url: `/blog/${id}`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetBlogsQuery,
  useGetBlogByIdQuery,
  useAddBlogMutation,
  useUpdateBlogMutation,
  useDeleteBlogMutation,
} = blogApi;
