import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.biopluskw.com/api/v1";

// Create the API slice using RTK Query
export const BrandApi = createApi({
  reducerPath: "BrandApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");

      // If a token exists, add it to the headers
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }

      return headers;
    },
  }),

  endpoints: (builder) => ({
    getBrands: builder.query({
      query: (params) => ({
        url: '/admin/brands',
        params: params, // Sends { page: 1, limit: 10 } as query params
      }),
    }),
    
    getBrand: builder.query({
      query: (id) => `/admin/brands/${id}`,
    }),
    addBrand: builder.mutation({
      query: (brand) => ({
        url: "/admin/brands",
        method: "POST",
        body: brand,
      }),
    }),
    updateBrand: builder.mutation({
      query: ({ id, brand }) => ({
        url: `/admin/brands/${id}`,
        method: "PUT",
        body: brand,
      }),
    }),
    deleteBrand: builder.mutation({
      query: (id) => ({
        url: `/admin/brands/${id}`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetBrandsQuery,
  useGetBrandQuery,
  useAddBrandMutation,
  useUpdateBrandMutation,
  useDeleteBrandMutation,
} = BrandApi;

