import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.biopluskw.com/api/v1";

// Create the API slice using RTK Query
export const CategoryApi = createApi({
  reducerPath: "CategoryApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");

      // If a token exists, add it to the headers
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }

      return headers;
    },
  }),

  endpoints: (builder) => ({
    getCategories: builder.query({
      query: ({ page, limit }) => ({
        url: '/admin/categories',
        params: { page, limit }, // Pass page and limit as query parameters
      }),
    }),
    addCategory: builder.mutation({
      query: (category) => ({
        url: "/admin/categories",
        method: "POST",
        body: category,
      }),
    }),
    updateCategory: builder.mutation({
      query: ({ id, category }) => ({
        url: `/admin/categories/${id}`,
        method: "PUT",
        body: category,
      }),
    }),
    deleteCategory: builder.mutation({
      query: (id) => ({
        url: `/admin/categories/${id}`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
 useGetCategoriesQuery,
 useAddCategoryMutation,
 useUpdateCategoryMutation,
 useDeleteCategoryMutation,
} = CategoryApi;
