import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.bridgeuni.com/api";

// Create the API slice using RTK Query
export const inquiresApi = createApi({
  reducerPath: "inquiresApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      const token = localStorage.getItem("token");
      if (token) {
        headers.set("authorization", `${token}`);
      }
      return headers;
    },
  }),

  endpoints: (builder) => ({
    getAllInquires: builder.query({
      query: () => ({
        url: "/inquires",
        method: "GET",
      }),
    }),
    deleteInquire: builder.mutation({
      query: (id) => ({
        url: `/inquires/${id}`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetAllInquiresQuery,
  useDeleteInquireMutation, // <-- new hook for deleting inquiries
} = inquiresApi;
