import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.bridgeuni.com/api";

// Create the API slice using RTK Query
export const joinUsApi = createApi({
  reducerPath: "joinUsApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      const token = localStorage.getItem("token");
      if (token) {
        headers.set("authorization", `${token}`);
      }
      return headers;
    },
  }),

  endpoints: (builder) => ({
    getAllJoinUsRequests: builder.query({
      query: () => ({
        url: "/joinUs",
        method: "GET",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetAllJoinUsRequestsQuery, // This is now a query hook
} = joinUsApi;
