import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.bridgeuni.com/api";

// Create the API slice using RTK Query
export const partnersApi = createApi({
  reducerPath: "partnersApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      const token = localStorage.getItem("token");
      if (token) {
        headers.set("authorization", `${token}`);
      }
      return headers;
    },
  }),

  endpoints: (builder) => ({
    getAllPartners: builder.query({
      query: () => ({
        url: "/partner",
        method: "GET",
      }),
    }),
    getPartnerById: builder.query({
      query: (id) => ({
        url: `/partner/${id}`,
        method: "GET",
      }),
    }),
    addPartner: builder.mutation({
      query: (data) => ({
        url: "/partner",
        method: "POST",
        body: data,
      }),
    }),
    updatePartner: builder.mutation({
      query: ({ id, data }) => ({
        url: `/partner/${id}`,
        method: "PUT",
        body: data,
      }),
    }),
    deletePartner: builder.mutation({
      query: (id) => ({
        url: `/partner/${id}`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetAllPartnersQuery, // This is now a query hook
  useGetPartnerByIdQuery,
  useAddPartnerMutation,
  useUpdatePartnerMutation,
  useDeletePartnerMutation,
} = partnersApi;
