import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.bridgeuni.com/api";

// Create the API slice using RTK Query
export const providerApi = createApi({
  reducerPath: "providerApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");
      // If a token exists, add it to the headers
      if (token) {
        headers.set("authorization", `${token}`);
      }
      return headers;
    },
  }),

  endpoints: (builder) => ({
    getAllProvider: builder.query({
      query: () => '/provider',
    }),
    getProvider: builder.query({
      query: (id) => '/provider/' + id,
    }),
    addProvider: builder.mutation({
      query: (data) => ({
        url: "/provider",
        method: "POST",
        body: data,
      }),
    }),
    updateProvider: builder.mutation({
      query: ({ id, data }) => ({
        url: `/provider/${id}`,
        method: "PUT",
        body: data,
      }),
    }),
    deleteProvider: builder.mutation({
      query: (id) => ({
        url: `/provider/${id}`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetAllProviderQuery,
  useGetProviderQuery,
  useAddProviderMutation,
  useUpdateProviderMutation,
  useDeleteProviderMutation
} = providerApi;
