import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.bridgeuni.com/api";

// Create the API slice using RTK Query
export const roleApi = createApi({
  reducerPath: "roleApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");

      // If a token exists, add it to the headers
      if (token) {
        headers.set("authorization", `${token}`);
      }

      return headers;
    },
  }),

  endpoints: (builder) => ({
    getRoles: builder.query({
      query: () => '/role/adminRole',
    }),
    getModules: builder.query({
      query: () => '/role/module',
    }),
    addRole: builder.mutation({
      query: (role) => ({
        url: "/role/adminRole",
        method: "POST",
        body: role,
      }),
    }),
    getRolePermissios:builder.query({
        query:(id) => `/role/rolePermission/${id}`
    }),

    updateRole: builder.mutation({
      query: ({ id, role }) => ({
        url: `/role/adminRole/${id}`,
        method: "PUT",
        body: role,
      }),
    }),

    deleteRole: builder.mutation({
      query: (id) => ({
        url: `/role/adminRole/${id}`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetRolesQuery,
  useGetModulesQuery,
  useAddRoleMutation,
  useUpdateRoleMutation,
  useDeleteRoleMutation,
  useGetRolePermissiosQuery
} = roleApi;
