import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.bridgeuni.com/api";

// Create the API slice using RTK Query
export const studentTestimonialApi = createApi({
  reducerPath: "studentTestimonialApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      const token = localStorage.getItem("token");
      if (token) {
        headers.set("authorization", `${token}`);
      }
      return headers;
    },
  }),

  endpoints: (builder) => ({
    getAllStudentTestimonials: builder.query({
      query: () => ({
        url: "/studentTestimonial",
        method: "GET",
      }),
    }),
    getStudentTestimonialById: builder.query({
      query: (id) => ({
        url: `/studentTestimonial/${id}`,
        method: "GET",
      }),
    }),
    addStudentTestimonial: builder.mutation({
      query: (data) => ({
        url: "/studentTestimonial",
        method: "POST",
        body: data,
      }),
    }),
    updateStudentTestimonial: builder.mutation({
      query: ({ id, data }) => ({
        url: `/studentTestimonial/${id}`,
        method: "PUT",
        body: data,
      }),
    }),
    deleteStudentTestimonial: builder.mutation({
      query: (id) => ({
        url: `/studentTestimonial/${id}`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetAllStudentTestimonialsQuery,
  useGetStudentTestimonialByIdQuery,
  useAddStudentTestimonialMutation,
  useUpdateStudentTestimonialMutation,
  useDeleteStudentTestimonialMutation,
} = studentTestimonialApi;
