import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.bridgeuni.com/api";

// Create the API slice using RTK Query
export const studyAbroadApi = createApi({
  reducerPath: "studyAbroadApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");
      // If a token exists, add it to the headers
      if (token) {
        headers.set("authorization", `${token}`);
      }
      return headers;
    },
  }),

  endpoints: (builder) => ({
    getAllAbroadCources: builder.query({
      query: () => '/studyAbroad',
    }),
    getAbroadCourse: builder.query({
      query: (id) => '/studyAbroad/' + id,
    }),
    addAbroadCourse: builder.mutation({
      query: (data) => ({
        url: "/studyAbroad",
        method: "POST",
        body: data,
      }),
    }),
    updateAbroadCourse: builder.mutation({
      query: ({ id, data }) => ({
        url: `/studyAbroad/${id}`,
        method: "PUT",
        body: data,
      }),
    }),
    deleteAbroadCourse: builder.mutation({
      query: (id) => ({
        url: `/studyAbroad/${id}`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
 useGetAllAbroadCourcesQuery,
 useGetAbroadCourseQuery,
 useAddAbroadCourseMutation,
 useUpdateAbroadCourseMutation,
 useDeleteAbroadCourseMutation
} = studyAbroadApi;
