import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define your base URL
const baseUrl = "https://back.biopluskw.com/api/v1";

// Create the API slice using RTK Query
export const TypeApi = createApi({
  reducerPath: "TypeApi",
  baseQuery: fetchBaseQuery({
    baseUrl,
    prepareHeaders: (headers) => {
      // Get the token from localStorage (or Redux state)
      const token = localStorage.getItem("token");

      // If a token exists, add it to the headers
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }

      return headers;
    },
  }),

  endpoints: (builder) => ({
    getTypes: builder.query({
      query: () => '/admin/product-types',
    }),
    getType: builder.query({
      query: (id) => `/admin/product-types/${id}`,
    }),
    addType: builder.mutation({
      query: (type) => ({
        url: "/admin/product-types",
        method: "POST",
        body: type,
      }),
    }),
    updateType: builder.mutation({
      query: ({ id, type }) => ({
        url: `/admin/product-types/${id}`,
        method: "PUT",
        body: type,
      }),
    }),
    deleteType: builder.mutation({
      query: (id) => ({
        url: `/admin/product-types/${id}`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by the API service
export const {
  useGetTypesQuery,
  useGetTypeQuery,
  useAddTypeMutation,
  useUpdateTypeMutation,
  useDeleteTypeMutation,
} = TypeApi;

